### ISSUE TITLE
Link redirecting to a 404

### ISSUE THREAD

**Issue by sohilpandya** [dwyl/dev-setup#10]
The following checkbox item in https://github.com/dwyl/dev-setup#checklist is redirecting users to a 404 link. Do we know where it's supposed to redirect the user to? 

>  Learn a handful of the most useful keyboard shortcuts

Should the link be to -> https://github.com/dwyl/dev-setup#our-most-used-text-editor-keyboard-shortcuts

**Comment by iteles** [comment]
@sohilpandya Yes, it should! Nice catch 👍

**Comment by danilocecilia** [comment]
The anchor link still has the problem.

**Comment by iteles** [comment]
@danilocecilia Thanks for reminding us of this! This repo could do with one big update!

If you'd like to PR in this change, please do 😊 Here is our contributing process for your reference: https://github.com/dwyl/contributing

_(and welcome to dwyl!)_ 🙌

**Comment by danilocecilia** [comment]
Thank you @iteles. 

I have cloned this repo and made the necessary change in order to make the anchor work, however, I can´t get the PR working. I am not sure if I am doing something wrong as I´m had never made a PR before.

Would you please consider helping me doing this? I would love to learn more and contribute to the dwyl!

Thanks!

**Comment by VimanyuAgg** [comment]
Submitted a PR to fix this. Please let me know in case of any issues :smiley:

**Comment by iteles** [comment]
:tada: Thanks @VimanyuAgg 😊
