### ISSUE TITLE
"Soft tabs"

### ISSUE THREAD

**Issue by LoganDark** [dwyl/dev-setup#15]
You're teaching beginners that using spaces for indentation is okay. And 2 spaces at that...

I get that some experienced developers have preferences, but you are telling people to _change the settings in their editor_ from the default to _your personal preference_.

Why do you have to tell people to change from hard tabs to soft tabs? It makes no difference. It's just an extra setting that's completely unnecessary to change. It's a setting you're making them _change from the default_ just because it's _your preference_.

I get that I'm biased, but objectively, this is at the very least _unnecessary_. People should not have to change settings that make absolutely no difference whatsoever just because you personally prefer using spaces for indentation (which tabs were designed for, in the first place).

This can also be said about tab length. Your preference does not matter. You're getting a beginner started. Why do you need them to change a completely pointless setting just to make you feel better? 2 wide tabs vs. 4 wide tabs has been debated for a long time. You're just picking a side because you're biased.

I would suggest leaving them at the default, instead of teaching beginners that one side is somehow more important than the other.

**Comment by nelsonic** [comment]
@LoganDark _thank you_ for opening this issue. 🎉 

It's _good_ to get this discussion _captured_ somewhere precisely so that people don't make the _assumption_ that a specific setting is because of a "personal preference". 

This repository is not intended as a "universal" developer setup for _everyone_ on GitHub.
(_otherwise we would have called it "The **Standard** Developer Setup **Everyone** Should Use or **`else`**!"_)

Perhaps we should _clarify_ that in the `README.md` ... 📝 

This repo is intended for _two_ audiences:

1. People who are **_learning_** how to code in the @dwyl online learning community (10k)
2. People who are **_paid_** to write code for a living by dwyl.com 

This can be illustrated by the following Venn Diagram: (_not to scale, simply to illustrate the subset_)

![dwyl-community-subset-venn-diagram](https://user-images.githubusercontent.com/194400/48290139-c99cde00-e469-11e8-8df6-9154a6e2724e.png)

i.e. this "dev-setup" guide is aimed at **0.02%** of the people in the world who _currently_ write code.

We want to _encourage_ people in this _tiny_ subset of the wider coding world to use "**two-spaces**".

Our ambition for @dwyl is to have an **_global online learning_ community** 🌍 
where _anyone_ can _collaboratively_ learn how to build useful things using code 
and to that end we have written _many_ tutorials/examples: https://github.com/dwyl/?q=learn

_Most_ of the examples _consistently_ use **two-spaces** for indentation 
and indeed that is the "_standard_" in both the JavaScript and Elixir communities 
(_our two most frequently used programming languages. Furthermore Rust and Haskell our two "future" languages are both 2-space dominated, so it's unlikely we are changing soon..._)
But perhaps the _most_ compelling reasoning for using 2-space over tabs is the fact that _most_ HTML is written with space-indentation and that is the language _most_ people learn _first_.

If someone in the learning community wants to _contribute_ an _improvement_ to one of the learning resources, it's _wise_ for them to configure their editor to avoid unnecessary changes in whitespace to an _entire_ file when they are only _editing/changing_ a _single line_ of text/code.

# But _Why...?_

Our **_medium-term_ goal** is to build a (_fully Open Source_) **_in-browser_ Learning Platform** ("MOOC") 
that will allow people from around the world to learn how to code  on _any_ device
from a shared ("locked down") Windows XP PC at an Internet Cafe where no Apps can be installed:

![internet-cafe-manilla](https://user-images.githubusercontent.com/194400/48291073-fe5e6480-e46c-11e8-9bcb-191a9f6d91a6.jpg)

to a Tablet/iPad without a physical keyboard:

![image](https://user-images.githubusercontent.com/194400/48290937-8728d080-e46c-11e8-8703-e47c3e014564.png)

Most Schools or Public Libraries where the "decision maker" or "IT person" does not _want_ the users to install any "developer tools" should not _exclude_ people from learning valuable Tech Skills!

[![image](https://user-images.githubusercontent.com/194400/48292269-8f373f00-e471-11e8-8aaf-14447152e606.png "photo credit: Dallas Public Library")](https://www.flickr.com/photos/dallaslibrary/8179009165/)



You Sir _obviously_ know a lot about building web-based text editors from your experience on "Nitrogen" https://github.com/allotropelabs/nitrogen ... so you _understand_ the _use-case_ of an Online Code Editor! 👍 

> _BTW: nitrogen demo https://app.nitrogenedit.com was unavailable when we tried to test-drive ..._
![image](https://user-images.githubusercontent.com/194400/48291365-1a163a80-e46e-11e8-828e-c7b1cd290b40.png)


But _many_ people still cannot _imagine/believe_ there are _Billions_ of people who _don't_ have their own **_MacBook Pro 15"_** on which they can install their preferred Text Editor or Terminal ... 👨‍💻 😮 

When our learning platform (_currently in development_) goes "_live_", 
using _spaces_ for indentation will be ***essential***; not a "personal preference"
because in _all_ Web Browsers, Tabs have a _very_ different "meaning" and _expected_ behaviour
from what they do in a Desktop-based Text Editor; pressing the **`Tab` key** while you are editing in a Browser changes cursor focus to the _next_ form field ... i.e. it will not insert a whitespace character.

We could _override_ the browser's default behaviour, but it would be at the expense of Accessibility ...

Further reading on Keyboard Navigation using Tabs for Accessibility:
+ https://www.nngroup.com/articles/keyboard-accessibility/
+ https://www.smashingmagazine.com/2018/07/web-with-just-a-keyboard/

<hr />

The Tabs vs. Spaces "debate" (_holy war_) will continue online for as long as there are people; 
if there's more than one way to do something, there will _always_ be differing "opinions" ...

[![image](https://user-images.githubusercontent.com/194400/48289229-986ede80-e466-11e8-8275-cc89096b991a.png)](https://youtu.be/V7PLxL8jIl8?t=22)
[https://youtu.be/V7PLxL8jIl8](https://youtu.be/V7PLxL8jIl8?t=22)

There is no shortage of "debate" (_flame war_) online as to what is "right" or "wrong" ... 
Felipe Hoffa (_developer advocate at Google_) made a good summary of the _Data_:
https://medium.com/@hoffa/400-000-github-repositories-1-billion-files-14-terabytes-of-code-spaces-or-tabs-7cfe0b5dd7fd
![image](https://user-images.githubusercontent.com/194400/48293476-310d5a80-e477-11e8-8231-8c9dcbb41c41.png)
Only the **`C`** and **`Go`** communities are using Tabs; 
in most other programming languages there is a _strong_ preference for spaces. 

# The World Voted. Two Spaces _Won_. 👾 

> To be clear: if it were up to me (_Nelson_) I would use Tabs and Emacs. 😮 (_logically_!)
> But I have to make decisions that are going to affect complete beginners 
for whom _my_ two "personal preferences" aren't going to be _relevant_. 

<hr />

_Respectfully_, we @dwyl aren't going to change the advice we give beginners 
in the @dwyl learning community  who _are_ able to define their own Text Editor Preferences, 
***because*** we _want_ people in the community to get used to **two-space** 
***so that*** when the ***tsunami*** of new people learning to code comes online in the next 5 years
all our learning materials/resources are prepared for the in-browser text editing experience.

**Comment by LoganDark** [comment]
@nelsonic Yeah, Nitrogen is down because the startup didn't exactly work out... I could spin up a personal instance for you if you'd like to try it out :>

**Comment by nelsonic** [comment]
@LoganDark I'm _always_ curious to try online text/code editors. 👍 
We've been using https://github.com/codemirror/codemirror ... 
What was the goal of the startup? 💭

**Comment by LoganDark** [comment]
There was a goal of education, the CEO had a really ambitious goal of this super awesome all-in-one textbook streaming / note taking application that he never had the funding to support. Nitrogen was my personal project before I agreed to brand it as one of their products.

Nitrogen uses Monaco as its editor, it doesn't really have the best code editing capabilities, not very powerful, it was just for a class of students. It just hosted websites for the teacher to view.

Nonetheless, when I'm less traumatized I could start up an instance for you, right now I'm dealing with some things though

**Comment by nelsonic** [comment]
@LoganDark makes perfect sense. 😞 
 I'd love to pick your brains on what you _learned_ in the process once you regain your inner peace. 
🌧 > ☀️ >🌈 > 😊 > 💬

**Comment by LoganDark** [comment]
@nelsonic Do you have a Discord for instant messaging? Cluttering up this issue is getting a bit boring. :P

I'll close it now, you can find my email on my profile if you'd like to send me the details in private. I don't like communicating over email/issues though. Discord is better :>
