### ISSUE TITLE
Update screensots

### ISSUE THREAD

**Issue by iteles** [dwyl/dev-setup#5]
GitHub has changed its UI, so we need to update the screenshots: https://github.com/dwyl/setup/blame/master/readme.md#L72

<img width="997" alt="screen shot 2016-09-06 at 13 38 35" src="https://cloud.githubusercontent.com/assets/4185328/18273834/44ecd16e-7437-11e6-8687-fa76c032c3e7.png">

**Comment by VimanyuAgg** [comment]
Created a pull request to fix this. Please let me know if there were any more screenshots to be updated.:neckbeard:

**Comment by nelsonic** [comment]
@VimanyuAgg updated screenshot looks great! (_thanks!_)
![change-to-ssh](https://user-images.githubusercontent.com/21698271/45860770-00daf280-bd37-11e8-92f8-34bb1ddf8152.png)

Almost a "_shame_" to "lose" the "old" image 
because it shows https://github.com/dwyl/start-here  back when it "only" had ***17 stars*** ... 😮 
But it's captured in the history and in this issue ⬆️ so people can see when we started ... 😉

**Comment by VimanyuAgg** [comment]
@nelsonic : Yeah I noticed that too! This issue is a remnant of the dwyl's humble beginnings :blush:

**Comment by iteles** [comment]
Thanks again @VimanyuAgg !
